### ISSUE TITLE
Application of Design Patterns

### ISSUE THREAD

**Issue by joaaguer** [Salgado2004/Trabalho-Final-LPOO-UFPR#53]
I reviewed and identified parts of your code that can be improved by applying design patterns, such as:

## Factory Method (Creational): 
> This pattern was chosen because it involves creating two subclasses that inherit from the superclass. The Factory Method is a creational design pattern that provides an interface for creating objects in a superclass while allowing subclasses to alter the type of objects that will be created. In this case, since we have a Conta class that has two subclasses, ContaCorrente and ContaInvestimento, it is advisable to use this design pattern.

![Creacional (1)](https://github.com/user-attachments/assets/273af525-f4c2-419e-94a6-dc7d0e60120d)

## Decorator (Structural): 
> The Decorator pattern is used to add functionalities to objects by placing these objects inside other objects, encapsulating these special objects with their functionalities. In this code, this design pattern can be implemented in the Conta class to add functionalities either in the short or long term. We can add more functionalities to the Conta class, such as setting transaction limits and other features.

![Decorator (1)](https://github.com/user-attachments/assets/1b6c9f0c-e169-4926-8c6a-f9e5ac76da5b)

## Observer (Behavioral):
> This design pattern is used when you want to notify about a change or event that happens to an object, and this notification is sent to the object that observes it. In the context of the code, we can see that the Conta class has two methods, deposita() and saca(). These methods are responsible for updating the user's account state. To obtain the account balance, there is getSaldo(), and the rest of the methods provide additional information. With the Observer design pattern, the Cliente will observe the Conta, and the former will be notified whenever a change or action occurs in the account.

![Observable](https://github.com/user-attachments/assets/78ae6d9b-d539-4048-8753-f3f52888f487)

(This is for a homework btw)

**Comment by Salgado2004** [comment]
I appreciate the review 😅 I'm gonna take a look at your suggestions and try to implement some of these patterns. Thank you very much. 
You said this is for a homework (🤣) that's very cool. I'm also studying.
Tell me... how did you find this project?

**Comment by Salgado2004** [comment]
> [!note]
> Original issue

I reviewed and identified parts of your code that can be improved by applying design patterns, such as:

## Factory Method (Creational):
> This pattern was chosen because it involves creating two subclasses that inherit from the superclass. The Factory Method is a creational design pattern that provides an interface for creating objects in a superclass while allowing subclasses to alter the type of objects that will be created. In this case, since we have a Conta class that has two subclasses, ContaCorrente and ContaInvestimento, it is advisable to use this design pattern.

![Creacional (1)](https://github.com/user-attachments/assets/273af525-f4c2-419e-94a6-dc7d0e60120d)


## Decorator (Structural):
> The Decorator pattern is used to add functionalities to objects by placing these objects inside other objects, encapsulating these special objects with their functionalities. In this code, this design pattern can be implemented in the Conta class to add functionalities either in the short or long term. We can add more functionalities to the Conta class, such as setting transaction limits and other features.

![Decorator (1)](https://github.com/user-attachments/assets/1b6c9f0c-e169-4926-8c6a-f9e5ac76da5b)


## Observer (Behavioral):
> This design pattern is used when you want to notify about a change or event that happens to an object, and this notification is sent to the object that observes it. In the context of the code, we can see that the Conta class has two methods, deposita() and saca(). These methods are responsible for updating the user's account state. To obtain the account balance, there is getSaldo(), and the rest of the methods provide additional information. With the Observer design pattern, the Cliente will observe the Conta, and the former will be notified whenever a change or action occurs in the account.

![Observable](https://github.com/user-attachments/assets/78ae6d9b-d539-4048-8753-f3f52888f487)

(This is for a homework btw)
